# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
title                    : "Sunit Singh"
title_separator          : "-"
name                     : "Sunit Singh"
description              : ""
url                      : https://iwinterknight.github.io
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "academicpages/academicpages.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "Sunit.png"
  name             : "Sunit Singh"
  pronouns         : "he/him"  
  bio              : "Machine Learning Engineer with 6 years of full time work experience in cloud-based ML"
  location         : "Columbus, Ohio, USA"
  employer         : "Ohio State University"
  uri              : # URL
  email            : "sunitsingh.bitsg@gmail.com" 

  # Academic websites
  github           : "iwinterknight"

  # Social media
  linkedin         : "sunit-singh-5025a331"


